{
  "branches": ["main"],
  "plugins": [
    ["@semantic-release/commit-analyzer", {
      "preset": "angular",
      "releaseRules": [
        {"type": "feat", "release": "minor"},
        {"type": "fix", "release": "patch"},
        {"type": "docs", "release": "patch"},
        {"type": "style", "release": "patch"},
        {"type": "refactor", "release": "patch"},
        {"type": "perf", "release": "patch"},
        {"type": "test", "release": "patch"},
        {"type": "ci", "release": "patch"},
        {"type": "chore", "release": "patch"},
        {"type": "revert", "release": "patch"},
        {"scope": "no-release", "release": false},
        {"type": "feat", "scope": "BREAKING", "release": "major"},
        {"type": "feat", "scope": "breaking", "release": "major"},
        {"type": "feat", "scope": "BREAKING CHANGE", "release": "major"},
        {"type": "feat", "scope": "breaking change", "release": "major"}
      ]
    }],
    "@semantic-release/release-notes-generator",
    ["@semantic-release/changelog", {
      "changelogFile": "CHANGELOG.md"
    }],
    ["@semantic-release/git", {
      "assets": ["pyproject.toml", "CHANGELOG.md"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }]
  ]
}